package ui;

import javax.swing.*;
import java.awt.*;

public class TmpGamePanel {
    private JPanel mainContainer;
    private JPanel rightContainer;
    private JPanel enemyMapContainer;
    private JPanel enemyLabelContainer;
    private JLabel enemyLabel;
    private JPanel btnContainer;
    private JPanel gameFieldsContainer;
    private JPanel leftContainer;
    private JPanel playerLabelContainer;
    private JLabel playerLabel;
    private JButton btnExit;
    private JButton btnLoad;
    private JButton btnSave;
    private JPanel exitBtnContainer;
    private JPanel saveGameContainer;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainContainer = new JPanel();
        mainContainer.setLayout(new GridBagLayout());
        gameFieldsContainer = new JPanel();
        gameFieldsContainer.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainContainer.add(gameFieldsContainer, gbc);
        leftContainer = new JPanel();
        leftContainer.setLayout(new GridBagLayout());
        gameFieldsContainer.add(leftContainer);
        playerLabelContainer = new JPanel();
        playerLabelContainer.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        leftContainer.add(playerLabelContainer, gbc);
        playerLabel = new JLabel();
        playerLabel.setText("PLAYER");
        playerLabelContainer.add(playerLabel);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 256;
        gbc.ipady = 256;
        leftContainer.add(panel1, gbc);
        rightContainer = new JPanel();
        rightContainer.setLayout(new GridBagLayout());
        gameFieldsContainer.add(rightContainer);
        enemyLabelContainer = new JPanel();
        enemyLabelContainer.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        rightContainer.add(enemyLabelContainer, gbc);
        enemyLabel = new JLabel();
        enemyLabel.setText("ENEMY");
        enemyLabelContainer.add(enemyLabel);
        enemyMapContainer = new JPanel();
        enemyMapContainer.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 256;
        gbc.ipady = 256;
        rightContainer.add(enemyMapContainer, gbc);
        btnContainer = new JPanel();
        btnContainer.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        mainContainer.add(btnContainer, gbc);
        exitBtnContainer = new JPanel();
        exitBtnContainer.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        btnContainer.add(exitBtnContainer, BorderLayout.WEST);
        btnExit = new JButton();
        btnExit.setText("EXIT");
        exitBtnContainer.add(btnExit);
        saveGameContainer = new JPanel();
        saveGameContainer.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        btnContainer.add(saveGameContainer, BorderLayout.CENTER);
        btnLoad = new JButton();
        btnLoad.setHorizontalAlignment(0);
        btnLoad.setText("LOAD");
        saveGameContainer.add(btnLoad);
        btnSave = new JButton();
        btnSave.setText("SAVE");
        saveGameContainer.add(btnSave);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainContainer;
    }
}
